In [2]:
import pandas as pd
data = pd.read_csv("data.csv")
data.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_4948\3631866713.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,X,Y,OBJECTID,advisorySpeed,areaUnitID,bicycle,bridge,bus,carStationWagon,cliffBank,...,train,tree,truck,unknownVehicleType,urban,vanOrUtility,vehicle,waterRiver,weatherA,weatherB
0,178.031840,-38.669793,1,NaN,544801.0,0.0,NaN,0.0,2.0,NaN,...,NaN,NaN,0.0,0.0,Urban,0.0,NaN,NaN,Fine,Null
1,175.264695,-37.785862,2,NaN,528900.0,0.0,NaN,0.0,2.0,NaN,...,NaN,NaN,0.0,0.0,Urban,0.0,NaN,NaN,Fine,Null
2,174.751715,-36.708328,3,NaN,507000.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,0.0,0.0,Urban,1.0,NaN,NaN,Fine,Null
3,172.394398,-43.609495,4,NaN,597513.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,Open,0.0,0.0,0.0,Fine,Null
4,168.385299,-46.417826,5,NaN,611500.0,0.0,NaN,0.0,1.0,NaN,...,NaN,NaN,0.0,0.0,Urban,1.0,NaN,NaN,Fine,Null

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821744 entries, 0 to 821743
Data columns (total 72 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   X                          821744 non-null  float64
 1   Y                          821744 non-null  float64
 2   OBJECTID                   821744 non-null  int64
 3   advisorySpeed              31344 non-null   float64
 4   areaUnitID                 821647 non-null  float64
 5   bicycle                    821739 non-null  float64
 6   bridge                     332913 non-null  float64
 7   bus                        821739 non-null  float64
 8   carStationWagon            821739 non-null  float64
 9   cliffBank                  332913 non-null  float64
 10  crashDirectionDescription  821744 non-null  object
 11  crashFinancialYear         821744 non-null  object
 12  crashLocation1             821744 non-null  object
 13  crashLocation2             820470 non-null  object
 14  crashRoadSideRoad          0 non-null       float64
 15  crashSeverity              821744 non-null  object
 16  crashSHDescription         821744 non-null  object
 17  crashYear                  821744 non-null  int64
 18  debris                     332913 non-null  float64
 19  directionRoleDescription   821672 non-null  object
 20  ditch                      332913 non-null  float64
 21  fatalCount                 821743 non-null  float64
 22  fence                      332913 non-null  float64
 23  flatHill                   821744 non-null  object
 24  guardRail                  332913 non-null  float64
 25  holiday                    44822 non-null   object
 26  houseOrBuilding            332913 non-null  float64
 27  intersection               0 non-null       float64
 28  kerb                       332913 non-null  float64
 29  light                      821744 non-null  object
 30  meshblockId                821647 non-null  float64
 31  minorInjuryCount           821743 non-null  float64
 32  moped                      821739 non-null  float64
 33  motorcycle                 821739 non-null  float64
 34  NumberOfLanes              819931 non-null  float64
 35  objectThrownOrDropped      332913 non-null  float64
 36  otherObject                332913 non-null  float64
 37  otherVehicleType           821739 non-null  float64
 38  overBank                   332913 non-null  float64
 39  parkedVehicle              332913 non-null  float64
 40  pedestrian                 26605 non-null   float64
 41  phoneBoxEtc                332913 non-null  float64
 42  postOrPole                 332913 non-null  float64
 43  region                     818556 non-null  object
 44  roadCharacter              821744 non-null  object
 45  roadLane                   821744 non-null  object
 46  roadSurface                821744 non-null  object
 47  roadworks                  332913 non-null  float64
 48  schoolBus                  821739 non-null  float64
 49  seriousInjuryCount         821743 non-null  float64
 50  slipOrFlood                332913 non-null  float64
 51  speedLimit                 820906 non-null  float64
 52  strayAnimal                332913 non-null  float64
 53  streetLight                696110 non-null  object
 54  suv                        821739 non-null  float64
 55  taxi                       821739 non-null  float64
 56  temporarySpeedLimit        12583 non-null   float64
 57  tlaId                      818556 non-null  float64
 58  tlaName                    818556 non-null  object
 59  trafficControl             821744 non-null  object
 60  trafficIsland              332913 non-null  float64
 61  trafficSign                332913 non-null  float64
 62  train                      332913 non-null  float64
 63  tree                       332913 non-null  float64
 64  truck                      821739 non-null  float64
 65  unknownVehicleType         821739 non-null  float64
 66  urban                      821744 non-null  object
 67  vanOrUtility               821739 non-null  float64
 68  vehicle                    332913 non-null  float64
 69  waterRiver                 332913 non-null  float64
 70  weatherA                   821744 non-null  object
 71  weatherB                   821739 non-null  object
dtypes: float64(50), int64(2), object(20)
memory usage: 451.4+ MB

In [4]:
data.shape

(821744, 72)

In [5]:
# Set display options to show all columns and info
pd.set_option('display.max_columns', None)
pd.set_option('display.max_info_columns', 100)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821744 entries, 0 to 821743
Data columns (total 72 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   X                          821744 non-null  float64
 1   Y                          821744 non-null  float64
 2   OBJECTID                   821744 non-null  int64
 3   advisorySpeed              31344 non-null   float64
 4   areaUnitID                 821647 non-null  float64
 5   bicycle                    821739 non-null  float64
 6   bridge                     332913 non-null  float64
 7   bus                        821739 non-null  float64
 8   carStationWagon            821739 non-null  float64
 9   cliffBank                  332913 non-null  float64
 10  crashDirectionDescription  821744 non-null  object
 11  crashFinancialYear         821744 non-null  object
 12  crashLocation1             821744 non-null  object
 13  crashLocation2             820470 non-null  object
 14  crashRoadSideRoad          0 non-null       float64
 15  crashSeverity              821744 non-null  object
 16  crashSHDescription         821744 non-null  object
 17  crashYear                  821744 non-null  int64
 18  debris                     332913 non-null  float64
 19  directionRoleDescription   821672 non-null  object
 20  ditch                      332913 non-null  float64
 21  fatalCount                 821743 non-null  float64
 22  fence                      332913 non-null  float64
 23  flatHill                   821744 non-null  object
 24  guardRail                  332913 non-null  float64
 25  holiday                    44822 non-null   object
 26  houseOrBuilding            332913 non-null  float64
 27  intersection               0 non-null       float64
 28  kerb                       332913 non-null  float64
 29  light                      821744 non-null  object
 30  meshblockId                821647 non-null  float64
 31  minorInjuryCount           821743 non-null  float64
 32  moped                      821739 non-null  float64
 33  motorcycle                 821739 non-null  float64
 34  NumberOfLanes              819931 non-null  float64
 35  objectThrownOrDropped      332913 non-null  float64
 36  otherObject                332913 non-null  float64
 37  otherVehicleType           821739 non-null  float64
 38  overBank                   332913 non-null  float64
 39  parkedVehicle              332913 non-null  float64
 40  pedestrian                 26605 non-null   float64
 41  phoneBoxEtc                332913 non-null  float64
 42  postOrPole                 332913 non-null  float64
 43  region                     818556 non-null  object
 44  roadCharacter              821744 non-null  object
 45  roadLane                   821744 non-null  object
 46  roadSurface                821744 non-null  object
 47  roadworks                  332913 non-null  float64
 48  schoolBus                  821739 non-null  float64
 49  seriousInjuryCount         821743 non-null  float64
 50  slipOrFlood                332913 non-null  float64
 51  speedLimit                 820906 non-null  float64
 52  strayAnimal                332913 non-null  float64
 53  streetLight                696110 non-null  object
 54  suv                        821739 non-null  float64
 55  taxi                       821739 non-null  float64
 56  temporarySpeedLimit        12583 non-null   float64
 57  tlaId                      818556 non-null  float64
 58  tlaName                    818556 non-null  object
 59  trafficControl             821744 non-null  object
 60  trafficIsland              332913 non-null  float64
 61  trafficSign                332913 non-null  float64
 62  train                      332913 non-null  float64
 63  tree                       332913 non-null  float64
 64  truck                      821739 non-null  float64
 65  unknownVehicleType         821739 non-null  float64
 66  urban                      821744 non-null  object
 67  vanOrUtility               821739 non-null  float64
 68  vehicle                    332913 non-null  float64
 69  waterRiver                 332913 non-null  float64
 70  weatherA                   821744 non-null  object
 71  weatherB                   821739 non-null  object
dtypes: float64(50), int64(2), object(20)
memory usage: 451.4+ MB

In [8]:
# Assuming df is your DataFrame containing the dataset
# Display column names vertically
for column in data.columns:
    print(column)

X
Y
OBJECTID
advisorySpeed
areaUnitID
bicycle
bridge
bus
carStationWagon
cliffBank
crashDirectionDescription
crashFinancialYear
crashLocation1
crashLocation2
crashRoadSideRoad
crashSeverity
crashSHDescription
crashYear
debris
directionRoleDescription
ditch
fatalCount
fence
flatHill
guardRail
holiday
houseOrBuilding
intersection
kerb
light
meshblockId
minorInjuryCount
moped
motorcycle
NumberOfLanes
objectThrownOrDropped
otherObject
otherVehicleType
overBank
parkedVehicle
pedestrian
phoneBoxEtc
postOrPole
region
roadCharacter
roadLane
roadSurface
roadworks
schoolBus
seriousInjuryCount
slipOrFlood
speedLimit
strayAnimal
streetLight
suv
taxi
temporarySpeedLimit
tlaId
tlaName
trafficControl
trafficIsland
trafficSign
train
tree
truck
unknownVehicleType
urban
vanOrUtility
vehicle
waterRiver
weatherA
weatherB